//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.18 at 03:02:37 PM EDT 
//


package edu.iu.mobiperv.esoochi.rest.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.iu.mobiperv.esoochi.rest.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InventoryItem_QNAME = new QName("", "inventoryItem");
    private final static QName _UserList_QNAME = new QName("", "userList");
    private final static QName _UserGroupList_QNAME = new QName("", "userGroupList");
    private final static QName _User_QNAME = new QName("", "user");
    private final static QName _UserGroup_QNAME = new QName("", "userGroup");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.iu.mobiperv.esoochi.rest.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InventoryItem }
     * 
     */
    public InventoryItem createInventoryItem() {
        return new InventoryItem();
    }

    /**
     * Create an instance of {@link UserList }
     * 
     */
    public UserList createUserList() {
        return new UserList();
    }

    /**
     * Create an instance of {@link UserGroupList }
     * 
     */
    public UserGroupList createUserGroupList() {
        return new UserGroupList();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link UserGroup }
     * 
     */
    public UserGroup createUserGroup() {
        return new UserGroup();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InventoryItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "inventoryItem")
    public JAXBElement<InventoryItem> createInventoryItem(InventoryItem value) {
        return new JAXBElement<InventoryItem>(_InventoryItem_QNAME, InventoryItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userList")
    public JAXBElement<UserList> createUserList(UserList value) {
        return new JAXBElement<UserList>(_UserList_QNAME, UserList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserGroupList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userGroupList")
    public JAXBElement<UserGroupList> createUserGroupList(UserGroupList value) {
        return new JAXBElement<UserGroupList>(_UserGroupList_QNAME, UserGroupList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userGroup")
    public JAXBElement<UserGroup> createUserGroup(UserGroup value) {
        return new JAXBElement<UserGroup>(_UserGroup_QNAME, UserGroup.class, null, value);
    }

}
